/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_szysky_note_androiddevseek_14_JNITest */

#ifndef _Included_com_szysky_note_androiddevseek_14_JNITest
#define _Included_com_szysky_note_androiddevseek_14_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_szysky_note_androiddevseek_14_JNITest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_szysky_note_androiddevseek_114_JNITest_get
  (JNIEnv *, jobject);

/*
 * Class:     com_szysky_note_androiddevseek_14_JNITest
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_szysky_note_androiddevseek_114_JNITest_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
